name: Deploy ke cPanel
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 8 * * *'

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: if [ -f package.json ]; then npm ci; fi
      - run: node tools/generate.js

      - name: Deploy file utama (bukan folder article)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 195.88.211.226
          username: deploy1@bandungbersuara.jabarinfo.id
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: /tribunpurwasuka/
          timeout: 500000
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/tools/**
            **/scripts/**
            **/article/**
            *.bak*
            *.ps1
            *.md
            articles_temp.json
            .DS_Store
            .env
            .env.local
            *.log
            netlify.toml
            package.json
            package-lock.json
            LICENSE.txt
            test.jpg

  deploy-articles:
    runs-on: ubuntu-latest
    needs: deploy-main  # jalankan setelah job pertama selesai
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: if [ -f package.json ]; then npm ci; fi
      - run: node tools/generate.js

      - name: Deploy folder article saja
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 195.88.211.226
          username: deploy1@bandungbersuara.jabarinfo.id
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./article/
          server-dir: /tribunpurwasuka/article/
          timeout: 500000
          dangerous-clean-slate: false
          exclude: |
            **/.git*
